repos:
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
   - id: black
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args:
       - --in-place
       - --remove-unused-variables
       - --remove-all-unused-imports
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args:
        - --line-length=88
        - --src=report_generator
        - --profile=black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
    - id: no-commit-to-branch
      args:
        - --pattern=develop|main
    - id: requirements-txt-fixer
    - id: trailing-whitespace
