author_name: DANIEL PINCHEIRA-DONOSO
data_set: /home/cush/a/data/excel_src/example_dataset_2_10000.xlsx
dir_path: /home/cush/a
project_name: a
report_name: Example Report
school_name: SCHOOL OF BIOLOGICAL SCIENCES
uni_name: QUEEN'S UNIVERSITY BELFAST
