# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report_generator/report_generator_gui/ui/report.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys

from PyQt5 import QtCore, QtWidgets

from report_generator.config import load_config
from report_generator.report_generator_cli.create_report import create_report


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 717)
        self.mainwin = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 551, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 190, 541, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.reportNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.reportNameLabel.setObjectName("reportNameLabel")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.reportNameLabel
        )
        self.reportNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.reportNameLineEdit.setObjectName("reportNameLineEdit")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.reportNameLineEdit
        )
        self.reportAuthorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.reportAuthorLabel.setObjectName("reportAuthorLabel")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.reportAuthorLabel
        )
        self.reportAuthorLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.reportAuthorLineEdit.setObjectName("reportAuthorLineEdit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.reportAuthorLineEdit
        )
        self.universityNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.universityNameLabel.setObjectName("universityNameLabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.universityNameLabel
        )
        self.universityNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.universityNameLineEdit.setObjectName("universityNameLineEdit")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.universityNameLineEdit
        )
        self.universitySchoolLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.universitySchoolLineEdit.setObjectName("universitySchoolLineEdit")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.universitySchoolLineEdit
        )
        self.universitySchoolLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.universitySchoolLabel.setObjectName("universitySchoolLabel")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.universitySchoolLabel
        )
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(370, 340, 161, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 541, 133))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.orderLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.orderLineEdit.setObjectName("orderLineEdit")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.orderLineEdit
        )
        self.familyLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.familyLabel.setObjectName("familyLabel")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.familyLabel
        )
        self.familyLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.familyLineEdit.setObjectName("familyLineEdit")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.familyLineEdit
        )
        self.genusLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.genusLabel.setObjectName("genusLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.genusLabel)
        self.genusLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.genusLineEdit.setObjectName("genusLineEdit")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.genusLineEdit
        )
        self.speciesLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.speciesLabel.setObjectName("speciesLabel")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.speciesLabel
        )
        self.speciesLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.speciesLineEdit.setObjectName("speciesLineEdit")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.speciesLineEdit
        )
        self.orderLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.orderLabel.setObjectName("orderLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.orderLabel)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 140, 541, 25))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.formLayoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clutchRangeMaxLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.clutchRangeMaxLabel.setObjectName("clutchRangeMaxLabel")
        self.horizontalLayout.addWidget(self.clutchRangeMaxLabel)
        self.clutchRangeMaxLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.clutchRangeMaxLineEdit.setMinimumSize(QtCore.QSize(216, 0))
        self.clutchRangeMaxLineEdit.setObjectName("clutchRangeMaxLineEdit")
        self.horizontalLayout.addWidget(self.clutchRangeMaxLineEdit)
        self.clutchRangeMinLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.clutchRangeMinLineEdit.setMaxLength(12767)
        self.clutchRangeMinLineEdit.setObjectName("clutchRangeMinLineEdit")
        self.horizontalLayout.addWidget(self.clutchRangeMinLineEdit)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 170, 541, 25))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.formLayoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clutchMinMaxLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.clutchMinMaxLabel.setObjectName("clutchMinMaxLabel")
        self.horizontalLayout_2.addWidget(self.clutchMinMaxLabel)
        self.clutchMinMaxLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.clutchMinMaxLineEdit.setObjectName("clutchMinMaxLineEdit")
        self.horizontalLayout_2.addWidget(self.clutchMinMaxLineEdit)
        self.clutchMinMinLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.clutchMinMinLineEdit.setObjectName("clutchMinMinLineEdit")
        self.horizontalLayout_2.addWidget(self.clutchMinMinLineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 600, 161, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(0, 200, 541, 25))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.formLayoutWidget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clutchMinMaxLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.clutchMinMaxLabel_2.setObjectName("clutchMinMaxLabel_2")
        self.horizontalLayout_3.addWidget(self.clutchMinMaxLabel_2)
        self.clutchMaxMinLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.clutchMaxMinLineEdit.setObjectName("clutchMaxMinLineEdit")
        self.horizontalLayout_3.addWidget(self.clutchMaxMinLineEdit)
        self.clutchMaxMaxLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.clutchMaxMaxLineEdit_2.setObjectName("clutchMaxMaxLineEdit_2")
        self.horizontalLayout_3.addWidget(self.clutchMaxMaxLineEdit_2)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(0, 230, 541, 25))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.formLayoutWidget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clutchMinMaxLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.clutchMinMaxLabel_3.setObjectName("clutchMinMaxLabel_3")
        self.horizontalLayout_4.addWidget(self.clutchMinMaxLabel_3)
        self.SVLMxMinLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.SVLMxMinLineEdit.setObjectName("SVLMxMinLineEdit")
        self.horizontalLayout_4.addWidget(self.SVLMxMinLineEdit)
        self.SVLMxMaxLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.SVLMxMaxLineEdit_2.setObjectName("SVLMxMaxLineEdit_2")
        self.horizontalLayout_4.addWidget(self.SVLMxMaxLineEdit_2)
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(0, 260, 541, 25))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.formLayoutWidget_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.clutchMinMaxLabel_4 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.clutchMinMaxLabel_4.setObjectName("clutchMinMaxLabel_4")
        self.horizontalLayout_5.addWidget(self.clutchMinMaxLabel_4)
        self.SVLMMxMinLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.SVLMMxMinLineEdit.setObjectName("SVLMMxMinLineEdit")
        self.horizontalLayout_5.addWidget(self.SVLMMxMinLineEdit)
        self.SVLMMxMaxLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.SVLMMxMaxLineEdit.setObjectName("SVLMMxMaxLineEdit")
        self.horizontalLayout_5.addWidget(self.SVLMMxMaxLineEdit)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(0, 290, 541, 25))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.formLayoutWidget_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clutchMinMaxLabel_5 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.clutchMinMaxLabel_5.setObjectName("clutchMinMaxLabel_5")
        self.horizontalLayout_6.addWidget(self.clutchMinMaxLabel_5)
        self.SVLFMxMin = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.SVLFMxMin.setObjectName("SVLFMxMin")
        self.horizontalLayout_6.addWidget(self.SVLFMxMin)
        self.SVLFMxMax = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.SVLFMxMax.setObjectName("SVLFMxMax")
        self.horizontalLayout_6.addWidget(self.SVLFMxMax)
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(0, 320, 541, 25))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.formLayoutWidget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.clutchMinMaxLabel_6 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.clutchMinMaxLabel_6.setObjectName("clutchMinMaxLabel_6")
        self.horizontalLayout_7.addWidget(self.clutchMinMaxLabel_6)
        self.EggDiameterMin = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.EggDiameterMin.setObjectName("EggDiameterMin")
        self.horizontalLayout_7.addWidget(self.EggDiameterMin)
        self.EggDiameterMax = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.EggDiameterMax.setObjectName("EggDiameterMax")
        self.horizontalLayout_7.addWidget(self.EggDiameterMax)
        self.formLayoutWidget_10 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(0, 350, 541, 25))
        self.formLayoutWidget_10.setObjectName("formLayoutWidget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.formLayoutWidget_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.clutchMinMaxLabel_7 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.clutchMinMaxLabel_7.setObjectName("clutchMinMaxLabel_7")
        self.horizontalLayout_8.addWidget(self.clutchMinMaxLabel_7)
        self.LongevityMin = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.LongevityMin.setObjectName("LongevityMin")
        self.horizontalLayout_8.addWidget(self.LongevityMin)
        self.LongevityMax = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.LongevityMax.setObjectName("LongevityMax")
        self.horizontalLayout_8.addWidget(self.LongevityMax)
        self.formLayoutWidget_11 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(0, 380, 541, 170))
        self.formLayoutWidget_11.setObjectName("formLayoutWidget_11")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.NestingSite = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.NestingSite.setObjectName("NestingSite")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.NestingSite
        )
        self.familyLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.familyLabel_2.setObjectName("familyLabel_2")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.familyLabel_2
        )
        self.MicroHabitat = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.MicroHabitat.setObjectName("MicroHabitat")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.MicroHabitat
        )
        self.genusLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.genusLabel_2.setObjectName("genusLabel_2")
        self.formLayout_3.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.genusLabel_2
        )
        self.Activity = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.Activity.setObjectName("Activity")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Activity)
        self.speciesLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.speciesLabel_2.setObjectName("speciesLabel_2")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.speciesLabel_2
        )
        self.GeographicRegion = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.GeographicRegion.setObjectName("GeographicRegion")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.GeographicRegion
        )
        self.orderLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.orderLabel_2.setObjectName("orderLabel_2")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.orderLabel_2
        )
        self.iUCNLabel = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.iUCNLabel.setObjectName("iUCNLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.iUCNLabel)
        self.IUCN = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.IUCN.setObjectName("IUCN")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.IUCN)
        self.popTrendLabel = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.popTrendLabel.setObjectName("popTrendLabel")
        self.formLayout_3.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.popTrendLabel
        )
        self.PopTrend = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.PopTrend.setObjectName("PopTrend")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.PopTrend)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 612, 20))
        self.menubar.setObjectName("menubar")
        self.menuReport_Generator = QtWidgets.QMenu(self.menubar)
        self.menuReport_Generator.setObjectName("menuReport_Generator")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuReport_Generator.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.create_report_button)
        self.pushButton_2.clicked.connect(self.create_report_button)
        self.set_config_values()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Report Generator"))
        self.reportNameLabel.setText(_translate("MainWindow", "Report Name"))
        self.reportAuthorLabel.setText(_translate("MainWindow", "Report Author"))
        self.universityNameLabel.setText(_translate("MainWindow", "University Name"))
        self.universitySchoolLabel.setText(
            _translate("MainWindow", "University School")
        )
        self.pushButton.setText(_translate("MainWindow", "Create Report"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Report Title")
        )
        self.familyLabel.setText(_translate("MainWindow", "Family"))
        self.genusLabel.setText(_translate("MainWindow", "Genus"))
        self.speciesLabel.setText(_translate("MainWindow", "Species"))
        self.orderLabel.setText(_translate("MainWindow", "Order                     "))
        self.clutchRangeMaxLabel.setText(
            _translate("MainWindow", "Clutch                    ")
        )
        self.clutchMinMaxLabel.setText(
            _translate("MainWindow", "Clutch Min             ")
        )
        self.pushButton_2.setText(_translate("MainWindow", "Create Report"))
        self.clutchMinMaxLabel_2.setText(
            _translate("MainWindow", "Clutch Max            ")
        )
        self.clutchMinMaxLabel_3.setText(
            _translate("MainWindow", "SVLMx                   ")
        )
        self.clutchMinMaxLabel_4.setText(
            _translate("MainWindow", "SVLMMx                ")
        )
        self.clutchMinMaxLabel_5.setText(
            _translate("MainWindow", "SVLFMx                 ")
        )
        self.clutchMinMaxLabel_6.setText(
            _translate("MainWindow", "Egg Diameter        ")
        )
        self.clutchMinMaxLabel_7.setText(
            _translate("MainWindow", "Longevity              ")
        )
        self.familyLabel_2.setText(_translate("MainWindow", "Micro Habitat"))
        self.genusLabel_2.setText(_translate("MainWindow", "Activity"))
        self.speciesLabel_2.setText(_translate("MainWindow", "Geographic Region"))
        self.orderLabel_2.setText(_translate("MainWindow", "Nesting Site"))
        self.iUCNLabel.setText(_translate("MainWindow", "IUCN"))
        self.popTrendLabel.setText(_translate("MainWindow", "Pop Trend"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2),
            _translate("MainWindow", "Filter Report"),
        )
        self.menuReport_Generator.setTitle(_translate("MainWindow", "Report Generator"))

    def clicked(self):
        """Click button message."""
        print("clicked")

    def set_config_values(self):
        config = load_config()
        self.reportNameLineEdit.setText(config["report_name"])
        self.reportAuthorLineEdit.setText(config["author_name"])
        self.universityNameLineEdit.setText(config["uni_name"])
        self.universitySchoolLineEdit.setText(config["school_name"])

    def create_report_button(self, MainWindow):
        """Create report button."""
        config = load_config()
        title = self.reportNameLineEdit.text()
        author = self.reportAuthorLineEdit.text()
        university = self.universityNameLineEdit.text()
        school = self.universitySchoolLineEdit.text()

        args = [title, author, university, school]
        source = os.path.join(config["dir_path"], "data", "database", "species.db")
        # create_report(source, title, author,university, school)
        options = {
            "--Activity": self.Activity.text(),
            "--Clutch": [
                self.clutchRangeMinLineEdit.text(),
                self.clutchRangeMaxLineEdit.text(),
            ],
            "--ClutchMax": [
                self.clutchMaxMinLineEdit.text(),
                self.clutchMaxMaxLineEdit_2.text(),
            ],
            "--ClutchMin": [
                self.clutchMinMinLineEdit.text(),
                self.clutchMinMaxLineEdit.text(),
            ],
            "--EggDiameter": [self.EggDiameterMin.text(), self.EggDiameterMax.text()],
            "--Family": self.familyLineEdit.text(),
            "--Genus": self.genusLineEdit.text(),
            "--GeographicRegion": self.GeographicRegion.text(),
            "--IUCN": self.IUCN.text(),
            "--Longevity": [self.LongevityMin.text(), self.LongevityMax.text()],
            "--MicroHabitat": self.MicroHabitat.text(),
            "--NestingSite": self.NestingSite.text(),
            "--ParityMode": [],
            "--PopTrend": self.PopTrend.text(),
            "--SVLFMx": [self.SVLFMxMin.text(), self.SVLFMxMax.text()],
            "--SVLMMx": [self.SVLMMxMinLineEdit.text(), self.SVLMMxMaxLineEdit.text()],
            "--SVLMx": [self.SVLMxMinLineEdit.text(), self.SVLMxMaxLineEdit_2.text()],
            "--Species": self.speciesLineEdit.text(),
            "--cli": False,
            "--gui": False,
            "--new": False,
            "--no-db": False,
            "--order_taxon_name": self.orderLineEdit.text(),
        }

        if all(args):
            print(f"Args: {title}, {author}, {university}, {school}")
            create_report(source, options, title, author, university, school)
            self.mainwin.close()
        else:
            print("All fields must be filled")


def main():
    """Application ui main."""
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
